server:
  port: 8081

spring:
  application:
    name: creditCalculator-1



logging:
  level:
    root: INFO
    edu.online.messenger: DEBUG
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

